RazorPageProject/Models/Data/DataBaseContext.cs
using Microsoft.EntityFrameworkCore;

namespace RazorPageProject.Models.Data
{
    public class DataBaseContext : DbContext
    {       
        public DataBaseContext(DbContextOptions<DataBaseContext> options) : base(options)
        {

        }

        public DbSet<Product> Product { get; set; }
    }
}

RazorPageProject/Models/Filters/AddHeaderAttribute.cs
using Microsoft.AspNetCore.Mvc.Filters;

namespace RazorPageProject.Models.Filters
{
    public class AddHeaderAttribute : Attribute, IResultFilter
    {
        private readonly string _name;
        private readonly string _value;

        public AddHeaderAttribute(string name, string value)
        {
            _name = name;
            _value = value;
        }

        public void OnResultExecuted(ResultExecutedContext context)
        {
            
        }

        public void OnResultExecuting(ResultExecutingContext context)
        {
            context.HttpContext.Response.Headers.Add(_name, new string[] { _value });
        }
    }
}

RazorPageProject/Models/Filters/MyPageFilter.cs
using Microsoft.AspNetCore.Mvc.Filters;

namespace RazorPageProject.Models.Filters
{
    public class MyPageFilter : Attribute, IPageFilter
    {
        public void OnPageHandlerExecuted(PageHandlerExecutedContext context)
        {
            // پیاده سازی کدهای موردنظر
        }

        public void OnPageHandlerExecuting(PageHandlerExecutingContext context)
        {
            
        }

        public void OnPageHandlerSelected(PageHandlerSelectedContext context)
        {
            
        }
    }
}

RazorPageProject/Models/Product.cs
namespace RazorPageProject.Models
{
    public class Product
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Price { get; set; }

        public string Description { get; set; }
    }
}

RazorPageProject/Areas/Admin/Pages/Category/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPageProject.Areas.Admin.Pages.Category
{
    public class IndexModel : PageModel
    {
        public string Name { get; set; }

        public void OnGet(int id, string name)
        {
            Name = name;
        }
    }
}

RazorPageProject/Areas/Admin/Pages/Test/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPageProject.Areas.Admin.Pages.Test
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }

        public void OnPost()
        {
        }

        public void OnPostSend()
        {
        }

        public void OnPostRegister()
        {
        }

        [NonHandler]
        public void OnPosTest()
        {
        }
    }
}

RazorPageProject/Pages/Admin/Product/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPageProject.Services;

namespace RazorPageProject.Pages.Admin.Product
{
    [Authorize]
    public class CreateModel : PageModel
    {
        [BindProperty]
        public ProductDTO Product { get; set; }

        private readonly IProductService _productService;

        public CreateModel(IProductService productService)
        {
            _productService = productService;
        }

        public void OnGet()
        {
        }

        public void OnPost()
        {
            var result = _productService.Add(Product);
        }
    }
}

RazorPageProject/Pages/Admin/Product/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPageProject.Services;

namespace RazorPageProject.Pages.Admin.Product
{
    public class DeleteModel : PageModel
    {       
        private readonly IProductService _productService;

        public DeleteModel(IProductService productService)
        {
            _productService = productService;
        }

        [BindProperty]
        public ProductDTO Product { get; set; }        
        
        public IActionResult OnGet(int? id)
        {
            if (id == null)
                return NotFound();

            Product = _productService.Find(id.Value);
            return Page();
        }

        public IActionResult OnPost()
        {
            _productService.Delete(Product.Id);
            return RedirectToPage("Index");
        }
    }
}

RazorPageProject/Pages/Admin/Product/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPageProject.Services;

namespace RazorPageProject.Pages.Admin.Product
{
    public class EditModel : PageModel
    {
        private readonly IProductService _productService;

        [BindProperty]
        public ProductDTO Product { get; set; }

        public EditModel(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult OnGet(int? id)
        {
            if (id == null)
                return NotFound();

            Product = _productService.Find(id.Value);
            return Page();
        }

        public IActionResult OnPost()
        {
            _productService.Edit(Product);
            return Page();
        }
    }
}

RazorPageProject/Pages/Admin/Product/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPageProject.Services;

namespace RazorPageProject.Pages.Admin.Product
{
    public class IndexModel : PageModel
    {
        public List<ProductDTO> Products { get; set; }

        private readonly IProductService _productService;

        public IndexModel(IProductService productService)
        {
            _productService = productService;
        }

        public void OnGet()
        {
            Products = _productService.List();
        }
    }
}

RazorPageProject/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorPageProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPageProject/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPageProject.Models.Filters;

namespace RazorPageProject.Pages
{
    //[MyPageFilter]
    //[AddHeader("MyHeader","test.net")]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public override void OnPageHandlerExecuted(PageHandlerExecutedContext context)
        {
            //نوشتن کدهای اختصاصی برای یک page

            base.OnPageHandlerExecuted(context);
        }
    }
}

RazorPageProject/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPageProject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPageProject/Areas/Admin/Pages/Category/Index.cshtml
@page "{id?}/{name=ali}"
@model RazorPageProject.Areas.Admin.Pages.Category.IndexModel
@{
}

<h1>دسته بندی</h1>

<h2> id = @RouteData.Values["id"] </h2>
<h3> name is : @Model.Name </h3>

RazorPageProject/Areas/Admin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RazorPageProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPageProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-page="/Category/Index">دسته بندی</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RazorPageProject - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RazorPageProject/Areas/Admin/Pages/Test/Index.cshtml
@page "{handler?}/{id?}"
@model RazorPageProject.Areas.Admin.Pages.Test.IndexModel
@{
}

<form method="post" asp-page-handler="Send">
    <h2>Send</h2>
    <button type="submit">send</button>
</form>

<hr />

<form method="post" asp-page-handler="Register">
    <h2>Register</h2>
    <button type="submit">Register</button>
</form>

<hr />

<form method="post">
    <h2>Send - Register</h2>
    <button type="submit" asp-page-handler="Send">send</button>
    <button type="submit" asp-page-handler="Register">Register</button>
</form>

RazorPageProject/Pages/Admin/Product/Create.cshtml
@page
@model RazorPageProject.Pages.Admin.Product.CreateModel
@{
}

<h1>افزودن محصول</h1>
<hr />
<div class="row">
    <form asp-page="Create" method="post">
        <div class="form-group">
            <label asp-for="Product.Name" class="form-label"></label>
            <input asp-for="Product.Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Product.Price" class="form-label"></label>
            <input asp-for="Product.Price" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Product.Description" class="form-label"></label>
            <textarea asp-for="Product.Description"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="ایجاد" class="btn btn-primary" />
        </div>
    </form>
</div>

RazorPageProject/Pages/Admin/Product/Delete.cshtml
@page
@model RazorPageProject.Pages.Admin.Product.DeleteModel
@*@{
    <div class="alert alert-info">
    <strong>@ViewData["message"]</strong>
    </div>
}*@
@*<h1>حذف محصول</h1>
<h3>آیا از حذف محصول مطمئن هستید؟</h3>*@
<div>
    <hr />
    <dl class="row">
        <dt class="col-md-2">
            <label asp-for="Product.Name"></label>
        </dt>
        <dd>
            <label>@Model.Product.Name</label>
        </dd>
    </dl>
    <form method="post" asp-page="Delete">
        <input type="hidden" asp-for="Product.Id" />
        <button type="submit" class="btn btn-danger">حذف کن</button>
        <a asp-page="./Index">برو به لیست</a>
    </form>
</div>

RazorPageProject/Pages/Admin/Product/Edit.cshtml
@page
@model RazorPageProject.Pages.Admin.Product.EditModel
@{
}

<h1>ویرایش</h1>

<div class="row">
    <form method="post">
        <input type="hidden" asp-for="Product.Id" />
        <div class="form-group">
            <label asp-for="Product.Name" class="form-label"></label>
            <input asp-for="Product.Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Product.Price" class="form-label"></label>
            <input asp-for="Product.Price" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Product.Description" class="form-label"></label>
            <textarea asp-for="Product.Description"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="ویرایش" class="btn btn-warning" />
        </div>
    </form>
</div>

RazorPageProject/Pages/Admin/Product/Index.cshtml
@page
@model RazorPageProject.Pages.Admin.Product.IndexModel
@{
}

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Products)
            {
                <tr>
                    <th>@item.Id</th>
                    <th>@item.Name</th>
                    <th>@item.Price</th>
                    <th>@item.Description</th>
                    <th>
                        <a asp-page = "Delete" asp-route-id = "@item.Id">حذف</a>
                    </th>
                    <th>
                        <a asp-page = "Edit" asp-route-id = "@item.Id">ویرایش</a>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

RazorPageProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorPageProject/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPageProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RazorPageProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPageProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-page="Category/Index">دسته بندی</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RazorPageProject - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>